### ISSUE TITLE
Readme required.

### ISSUE THREAD

**Issue by Kushagra8888** [Kushagra8888/Scrabble#1]
Description of algorithm and and division of work.

**Comment by Kushagra8888** [comment]
The allocation of work needs to mentioned in the readme.

**Comment by Kushagra8888** [comment]
Readme needs to be updated according to the new approach

**Comment by khushah** [comment]
Kushagra looks like we have updated the readme, can we close this issue now?

**Comment by Kushagra8888** [comment]
Closing
