### ISSUE TITLE
Add test cases

### ISSUE THREAD

**Issue by Kushagra8888** [Kushagra8888/Scrabble#13]
add unit tests for each function

**Comment by khushah** [comment]
Are we adding test cases manually or writing unit test code for the same?

**Comment by ipsi16** [comment]
we can use CUTE Framework

**Comment by Kushagra8888** [comment]
Anyone having experience with cppunit?

**Comment by Kushagra8888** [comment]
We can explore NUnit

**Comment by aashishRamamurthy** [comment]
Who is doing this?

**Comment by Kushagra8888** [comment]
No one has started yet.

**Comment by khushah** [comment]
Anyone testing with nunit? I tried something called google test but it needed visual studio ...

**Comment by Kushagra8888** [comment]
its a nightmare.
