### ISSUE TITLE
create core functional code

### ISSUE THREAD

**Issue by Kushagra8888** [Kushagra8888/Scrabble#3]
- Given a rack of letters, find the top 5 scoring words

**Comment by garvitjain314** [comment]
In the core functional code, how is team 1 dealing with blank spaces in the rack?
Lets say the rack is a b \* c d \* l, \* being a blank tile. Do you find all words that match with abcdl ignoring the blank tiles?

**Comment by Kushagra8888** [comment]
We need to create a new Hash Map while scanning the dictionary called wordsOfLength with Key -> length of word, values -> all possible words having that value.

**Comment by garvitjain314** [comment]
Note that there can be multiple keys if the user does not specify a fixed word length. He might say, I need a 6 to 8 length string with c and p in them separated by a distance of 2. How is this case handled?

**Comment by Kushagra8888** [comment]
How would you input such a constraint to start with?

**Comment by mtbar131** [comment]
We need to consider the condition mentioned by garvit

**Comment by Kushagra8888** [comment]
We need the constrained as an input to the program, how will such a constraint be input?

**Comment by DhanyaHN** [comment]
What all constraints are we handling?

**Comment by DhanyaHN** [comment]
lets do 2 now
Length of the word and one character at a given position

**Comment by garvitjain314** [comment]
Dhanya, we can't consider just one particular case. We need to take care of whatever that can be possible.

**Comment by Kushagra8888** [comment]
For the anagramCollection data structure, should we also add the score as the first value?
