### ISSUE TITLE
handle added constraints

### ISSUE THREAD

**Issue by Kushagra8888** [Kushagra8888/Scrabble#5]
handle cases where certain letters must appear at pre-defined positions and the length of word is fixed

Example **c**p**

**Comment by Kushagra8888** [comment]
add a function that maps a constraint from string format to a regular expression representing the constraints. Use this to select valid words form the wordsOfLength Hash Map

 wordsOfLength is a hashMap with Key -> length of word, values -> all possible words having that value.

**Comment by mtbar131** [comment]
lets fix the input format as [a-z] and _, _.
where '_' shows the distance between two chars and _ is a space

**Comment by Kushagra8888** [comment]
@mtbar131 We can go for this.

**Comment by mtbar131** [comment]
Lets make it '*' for blank tile and '_' for distance between two chars. Now in rack we will use \* to denote blank tiles and in constraints we will accept chars and '_' to denote distance between two chars. Now this is final!

**Comment by khushah** [comment]
for input to constraint problem, we have two possibilities _b_d_ _ and _b_d_???

**Comment by mtbar131** [comment]
There are 3 types of constraints possible:
1 length of the word: for example if we need all 4 char words then constraint will be "____"
2 words made up of given characters exmple "abcd"
3 words made up of given as well as other chars example "__b_cd_"

**Comment by khushah** [comment]
we cant take ____ as input if user wants just 4 letter words out of the rack...

**Comment by Kushagra8888** [comment]
____ essentially means that length is constrained to only 4.

**Comment by aashishRamamurthy** [comment]
Can we switch to ',' instead of an underscore?

**Comment by Kushagra8888** [comment]
How about using numbers 
E.g : 1a5b4 
would mean a total of 12 letters with a at 2nd pos and b at 7th pos

**Comment by ipsi16** [comment]
if input is something like this:__c__p_
essentially regex for comparision should look something like [a-z]_c[a-z]{2}p_ right?

**Comment by ipsi16** [comment]
sorry [a-z] \* c[a-z] {2} p

**Comment by Kushagra8888** [comment]
[a-z]{2}c[a-z]{2}p[a-z]

**Comment by ipsi16** [comment]
[a-z]{0,2}c[a-z]{2}p[a-z]{0,1}

**Comment by ipsi16** [comment]
in the regex {0,2} denotes there can be UPTO 2 letters in front of c(not necessarily 2, it can be less)
